
package com.hef.spittr.jaxws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SpitterServiceEndpoint", targetNamespace = "http://jaxws.remoting.spittr.hef.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SpitterServiceEndpoint {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "saveSpitter", targetNamespace = "http://jaxws.remoting.spittr.hef.com/", className = "com.hef.spittr.jaxws.client.SaveSpitter")
    @ResponseWrapper(localName = "saveSpitterResponse", targetNamespace = "http://jaxws.remoting.spittr.hef.com/", className = "com.hef.spittr.jaxws.client.SaveSpitterResponse")
    @Action(input = "http://jaxws.remoting.spittr.hef.com/SpitterServiceEndpoint/saveSpitterRequest", output = "http://jaxws.remoting.spittr.hef.com/SpitterServiceEndpoint/saveSpitterResponse")
    public void saveSpitter(
        @WebParam(name = "arg0", targetNamespace = "")
        Spitter arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.hef.spittr.jaxws.client.Spitter
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findSpitterById", targetNamespace = "http://jaxws.remoting.spittr.hef.com/", className = "com.hef.spittr.jaxws.client.FindSpitterById")
    @ResponseWrapper(localName = "findSpitterByIdResponse", targetNamespace = "http://jaxws.remoting.spittr.hef.com/", className = "com.hef.spittr.jaxws.client.FindSpitterByIdResponse")
    @Action(input = "http://jaxws.remoting.spittr.hef.com/SpitterServiceEndpoint/findSpitterByIdRequest", output = "http://jaxws.remoting.spittr.hef.com/SpitterServiceEndpoint/findSpitterByIdResponse")
    public Spitter findSpitterById(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.hef.spittr.jaxws.client.Spitter>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllSpitters", targetNamespace = "http://jaxws.remoting.spittr.hef.com/", className = "com.hef.spittr.jaxws.client.FindAllSpitters")
    @ResponseWrapper(localName = "findAllSpittersResponse", targetNamespace = "http://jaxws.remoting.spittr.hef.com/", className = "com.hef.spittr.jaxws.client.FindAllSpittersResponse")
    @Action(input = "http://jaxws.remoting.spittr.hef.com/SpitterServiceEndpoint/findAllSpittersRequest", output = "http://jaxws.remoting.spittr.hef.com/SpitterServiceEndpoint/findAllSpittersResponse")
    public List<Spitter> findAllSpitters();

}
