
package com.hef.spittr.jaxws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SpitterService", targetNamespace = "http://jaxws.remoting.spittr.hef.com/", wsdlLocation = "http://localhost:8088/services/SpitterService?wsdl")
public class SpitterService
    extends Service
{

    private final static URL SPITTERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SPITTERSERVICE_EXCEPTION;
    private final static QName SPITTERSERVICE_QNAME = new QName("http://jaxws.remoting.spittr.hef.com/", "SpitterService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/services/SpitterService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SPITTERSERVICE_WSDL_LOCATION = url;
        SPITTERSERVICE_EXCEPTION = e;
    }

    public SpitterService() {
        super(__getWsdlLocation(), SPITTERSERVICE_QNAME);
    }

    public SpitterService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SPITTERSERVICE_QNAME, features);
    }

    public SpitterService(URL wsdlLocation) {
        super(wsdlLocation, SPITTERSERVICE_QNAME);
    }

    public SpitterService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SPITTERSERVICE_QNAME, features);
    }

    public SpitterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SpitterService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SpitterServiceEndpoint
     */
    @WebEndpoint(name = "SpitterServiceEndpointPort")
    public SpitterServiceEndpoint getSpitterServiceEndpointPort() {
        return super.getPort(new QName("http://jaxws.remoting.spittr.hef.com/", "SpitterServiceEndpointPort"), SpitterServiceEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SpitterServiceEndpoint
     */
    @WebEndpoint(name = "SpitterServiceEndpointPort")
    public SpitterServiceEndpoint getSpitterServiceEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jaxws.remoting.spittr.hef.com/", "SpitterServiceEndpointPort"), SpitterServiceEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SPITTERSERVICE_EXCEPTION!= null) {
            throw SPITTERSERVICE_EXCEPTION;
        }
        return SPITTERSERVICE_WSDL_LOCATION;
    }

}
